# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a4dcf40e2e22f2ed74c8fda3f893bf632c811c7ed0d9a64b575d113168e39ba204ffe66bc86754fc12747dd8295a0b414c89e743e66c18a1aec868324457b96

test:
  secret_key_base: ae5454e919072f35580e188c87d3c94042f692f55905b3d3b4f5473129638dafffc3d3050f735da67c31b21bbd5ad9823878df1311476b01cbdaeccc5dfd4810

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
